"""Push finetune_dataset to HuggingFace Hub as DownFlow/nsfw."""

import json
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

from datasets import Dataset, DatasetDict, Features, Image as HFImage, Value
from huggingface_hub import HfApi
from PIL import Image as PILImage

DATASET_DIR = Path(__file__).parent.parent / "finetune_dataset"
REPO_ID = "DownFlow/nsfw"
HF_TOKEN = os.environ["HF_TOKEN"]

README = """\
---
license: other
task_categories:
- text-to-image
language:
- en
- zh
tags:
- nsfw
- image-generation
- finetune
- synthetic-captions
size_categories:
- n<1K
---

# DownFlow/nsfw

Alright so I spent way too long on this and figured I'd just throw it up here.

277 images with bilingual captions (EN + Simplified Chinese) for fine-tuning image generation models.
Captions are generated by a vision-language model and describe the actual content — scene, pose, body parts, clothing, lighting, art style. No fluff. No apologies.

## Columns

| column | type | what it is |
|--------|------|------------|
| `image` | PIL image | the cropped training image |
| `text_en` | string | English caption (~50–120 words) |
| `text_cn` | string | Simplified Chinese caption (~50–150 chars) |

## Images

All images are preprocessed for training:
- Top 5% strip removed (watermark zone)
- Aspect-preserving resize (shortest side = 512px)
- Both dimensions floored to nearest multiple of 16
- Saved as JPEG

## Usage

```python
from datasets import load_dataset

ds = load_dataset("DownFlow/nsfw", split="train")
# ds[0].keys() → image, text_en, text_cn

# For training, pick a language:
captions = [row["text_en"] for row in ds]
```

## Why bilingual

Training on both languages gives you a model that responds to prompts in either EN or ZH.
Practically useful if your user base isn't exclusively English-speaking.

## Notes

- ~277 samples is small. Use this as a starting point or merge with larger datasets.
- Captions are auto-generated and occasionally imperfect. Spot-check before relying on them.
- Images were collected from commercial fashion/lifestyle sources and have been preprocessed.
  Original watermarks are stripped. Use responsibly.

This dataset is intended for research and fine-tuning of generative image models.
"""

def main():
    print("Loading metadata...")
    rows = [json.loads(l) for l in open(DATASET_DIR / "metadata.jsonl")]
    # filter to ok entries only
    rows = [r for r in rows if r.get("status", "ok") in ("ok", "ok_mono")]
    print(f"  {len(rows)} rows after status filter")

    print("Loading images...")
    images = []
    text_en = []
    text_cn = []

    for r in rows:
        img_rel = r["file_name"].replace("images/", "")
        img_path = DATASET_DIR / "images" / img_rel
        try:
            img = PILImage.open(img_path).convert("RGB")
        except Exception as e:
            print(f"  SKIP {img_path}: {e}")
            continue
        images.append(img)
        text_en.append(r.get("text_en", ""))
        text_cn.append(r.get("text_zh", ""))  # rename text_zh → text_cn

    print(f"  {len(images)} images loaded")

    print("Building dataset...")
    ds = Dataset.from_dict(
        {"image": images, "text_en": text_en, "text_cn": text_cn},
        features=Features({
            "image": HFImage(),
            "text_en": Value("string"),
            "text_cn": Value("string"),
        }),
    )
    print(ds)

    print(f"Pushing to {REPO_ID} ...")
    api = HfApi(token=HF_TOKEN)
    api.create_repo(repo_id=REPO_ID, repo_type="dataset", exist_ok=True, private=False)

    ds.push_to_hub(
        REPO_ID,
        token=HF_TOKEN,
        split="train",
    )

    print("Uploading README...")
    api.upload_file(
        path_or_fileobj=README.encode(),
        path_in_repo="README.md",
        repo_id=REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN,
    )

    print(f"\nDone! https://huggingface.co/datasets/{REPO_ID}")


if __name__ == "__main__":
    main()
